import type { Metadata } from 'next'
import { ThemeProvider } from '@/hooks/theme-provider'
import { Montserrat } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import Header from '@/components/header'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className={cn('max-w-screen overflow-x-hidden antialiased', montserrat.className)}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <Header />

          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
